sudo: false
language: python
python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7
  - pypy
  - pypy3
install:
- pip install -U tox-travis
script: tox
before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - "$HOME/.cache/pip"
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: starofrainnight
  password:
    secure: GZkvQHF75Dj7xNIjMGW8jvCrdPWHdSJHJ4J2cB9Xgk4SQV5PeHUUSkKPZBm82stcG+rbNlsBRI/O42dhGt/ZuA7sexbH4I0fsFyNVHiFDWqojFl3w2yNWvgrV2WmkdIzLEtqJc00O7wMdHYLBNvT7mx98mjSpzK/KQ18II3HfuL8PA3KkV7ZZIkzWqhOIfpYxT4f6ybtM0ju+Dw/Iz5dvK0CTGi9ta1FVNSxA8xQFsRPgFFzioE6scGleGiJDFD+xmyWv31UHf5cbF71ESK5xASdNY0sna0wRgJeSJlLNls3J3tn7tzED0EmFpSg+dYm2aPyqFLe73EVYgdxIQK75sYAzGlpImeUoDMzauMDfFzdF6BEiSPG+AL/v4xAZTtCMGnJ2SUAkQOJcm+mQ2xIIMzDQ/4Sc1ivKtDz9AZJ9Jh9i63UaAvLIZszmZ9+LVi1sSuQ76AOUf8wmLgCS+nbt498tBFlT0xhflrZ1TMR/4NAjNSJxjvnrrjDapDQo5+XDWVGrgR/Rzg5JJdAUfjiA3gPsYgAltIenAcX2rI4MdnBA9iitm3oYbamOb+C3n4c75y5GkQ+Cx4bjf2705LkYAgK3MZZcxQXU9kWJABh93chpNgvtxHDZga6CpK2yPVA1UaZXGIvBwF5UJGWH/63Vme1QQ0iIG8zttu/0k6hswk=
  on:
    tags: true
    repo: starofrainnight/qchviewer
    condition: "$TOXENV == py34"
